package io.misode.mobile

/**
 * misode 生成器 id → 中文名。
 *
 * bridge.getGenerators() 内部写死了英文词条（enStrings），
 * 页面语言切到中文后，网页里的列表会变中文，
 * 但原生侧拿到的 title 仍是英文 —— 这里按同一份词条补上。
 *
 * 数据来自 misode-web 的 src/locales/zh-cn.json（MIT）。
 */
internal object GeneratorZh {

	private val MAP: Map<String, String> = mapOf(
		"loot_table" to "战利品表",
		"predicate" to "谓词",
		"item_modifier" to "物品修饰器",
		"advancement" to "进度",
		"recipe" to "配方",
		"chat_type" to "聊天类型",
		"damage_type" to "伤害类型",
		"trim_material" to "盔甲纹饰材料",
		"trim_pattern" to "盔甲纹饰图案",
		"banner_pattern" to "旗帜图案",
		"wolf_variant" to "狼变种",
		"wolf_sound_variant" to "狼音效变种",
		"enchantment" to "魔咒",
		"enchantment_provider" to "魔咒提供器",
		"painting_variant" to "画变种",
		"jukebox_song" to "唱片机曲目",
		"instrument" to "乐器",
		"trial_spawner" to "试炼刷怪笼",
		"pig_variant" to "猪变种",
		"cat_variant" to "猫变种",
		"frog_variant" to "青蛙变种",
		"chicken_variant" to "鸡变种",
		"cow_variant" to "牛变种",
		"dialog" to "对话框",
		"test_instance" to "测试实例",
		"test_environment" to "测试环境",
		"timeline" to "时间线",
		"zombie_nautilus_variant" to "僵尸鹦鹉螺",
		"text_component" to "文本组件",
		"pack_mcmeta" to "pack.mcmeta",
		"dimension" to "维度",
		"dimension_type" to "维度类型",
		"worldgen/biome" to "生物群系",
		"worldgen/configured_carver" to "已配置的雕刻器",
		"worldgen/configured_feature" to "已配置的地物",
		"worldgen/placed_feature" to "已放置的地物",
		"worldgen/density_function" to "密度函数",
		"worldgen/noise" to "噪声",
		"worldgen/noise_settings" to "噪声设置",
		"worldgen/configured_structure_feature" to "结构地物",
		"worldgen/structure" to "结构",
		"worldgen/structure_set" to "结构集",
		"worldgen/configured_surface_builder" to "地表生成器",
		"worldgen/processor_list" to "处理器列表",
		"worldgen/template_pool" to "模板池",
		"worldgen/world_preset" to "世界预设",
		"worldgen/flat_level_generator_preset" to "超平坦世界预设",
		"world" to "世界设置",
		"tag/block" to "方块标签",
		"tag/entity_type" to "实体类型标签",
		"tag/fluid" to "流体标签",
		"tag/game_event" to "游戏事件标签",
		"tag/item" to "物品标签",
		"tag/damage_type" to "伤害类型标签",
		"tag/dialog" to "对话框标签",
		"tag/worldgen/biome" to "生物群系标签",
		"tag/worldgen/structure" to "结构标签",
		"tag/worldgen/structure_set" to "结构集标签",
		"tag/worldgen/flat_level_generator_preset" to "超平坦预设标签",
		"tag/worldgen/world_preset" to "世界预设标签",
		"tag/banner_pattern" to "旗帜图案标签",
		"tag/cat_variant" to "猫变种标签",
		"tag/enchantment" to "魔咒标签",
		"tag/instrument" to "乐器标签",
		"tag/painting_variant" to "画变种标签",
		"tag/point_of_interest_type" to "兴趣点类型标签",
		"tag/timeline" to "时间线标签",
		"tag/zombie_nautilus_variant" to "僵尸鹦鹉螺标签",
		"block_definition" to "方块状态",
		"item_definition" to "物品",
		"model" to "模型",
		"texture_meta" to "纹理元数据",
		"equipment" to "装备",
		"lang" to "语言",
		"font" to "字体",
		"atlas" to "图集",
		"post_effect" to "后处理管线程序文件",
		"ad_astra:planets" to "Ad Astra 星球",
		"fabric:fabric_mod_json" to "fabric.mod.json",
		"fabric:dependency_overrides" to "fabric_loader_dependencies.json",
		"immersive_weathering:block_growth" to "方块生长",
		"neoforge:biome_modifier" to "生物群系修改器",
		"neoforge:data_map_acceptable_villager_distances" to "村民探测距离数据映射表",
		"neoforge:data_map_compostables" to "可以堆肥的物品合成配方",
		"neoforge:data_map_furnace_fuels" to "熔炉内的配方",
		"neoforge:data_map_monster_room_mobs" to "刷怪笼怪物数据表",
		"neoforge:data_map_oxidizables" to "可氧化方块数据表",
		"neoforge:data_map_parrot_imitations" to "鹦鹉模仿怪物声音数据",
		"neoforge:data_map_raid_hero_gifts" to "村庄英雄奖励配置",
		"neoforge:data_map_strippables" to "可去皮原木数据映射表",
		"neoforge:data_map_vibration_frequencies" to "振动频率数据（关于红石）",
		"neoforge:data_map_villager_types" to "村民群系类别数据映射表",
		"neoforge:data_map_waxables" to "可以上蜡的方块表",
		"neoforge:structure_modifier" to "结构修改器",
		"ohthetreesyoullgrow:configured_feature" to "OTTYG地物",
		"sky_aesthetics:sky" to "自定义天空",
		"create:recipes" to "机械动力配方",
		"thermoo:environment_provider" to "环境提供者",
		"thermoo:environment" to "环境",
		"thermoo:temperature_effect" to "温度效果",
		"thermoo:predicate" to "Thermoo谓词",
		"pixelmon:growth" to "像素宝可梦体型",
		"pixelmon:type" to "像素宝可梦属性",
		"pixelmon:spawn_replacement" to "像素宝可梦 生成取代规则",
		"pixelmon:interaction_event" to "像素宝可梦交互事件",
		"pixelmon:research" to "像素宝可梦田野调查",
		"pixelmon:research_trigger" to "像素宝可梦田野调查触发器",
		"pixelmon:npc_preset" to "像素宝可梦NPC预设",
		"pixelmon:pokedex_trigger" to "图鉴触发器",
		"pixelmon:pokedex_region" to "区域",
		"pixelmon:pokedex" to "宝可梦图鉴",
		// 以下词条在 zh-cn.json 里没有，按 id 含义补译
		"pig_sound_variant" to "猪叫声变体",
		"cat_sound_variant" to "猫叫声变体",
		"chicken_sound_variant" to "鸡叫声变体",
		"cow_sound_variant" to "牛叫声变体",
		"context_float_provider" to "上下文浮点提供器",
		"context_int_provider" to "上下文整数提供器",
		"world_clock" to "世界时钟",
		"villager_trade" to "村民交易",
		"trade_set" to "交易组",
		"sulfur_cube_archetype" to "硫方块原型",
		"slot_source" to "槽位来源",
		"decorated_pot_pattern" to "饰纹陶罐图案",
		"block_transformer" to "方块转换器",
		"worldgen/carver" to "世界生成 · 洞穴雕刻器",
		"worldgen/feature" to "世界生成 · 地物",
		"worldgen/material_condition" to "世界生成 · 材质条件",
		"worldgen/material_rule" to "世界生成 · 材质规则",
		"tag/villager_trade" to "标签 · 村民交易",
		"tag/trade_set" to "标签 · 交易组",
		"sounds" to "声音事件",
	)

	/** 取中文名；没有对应词条时返回 null，让调用方退回英文。 */
	fun of(id: String): String? = MAP[id]

	/** 给一整份 [GeneratorInfo] 列表补中文标题。 */
	fun apply(list: List<GeneratorInfo>): List<GeneratorInfo> =
		list.map { g ->
			val zh = MAP[g.id]
			if (zh.isNullOrBlank() || zh == g.title) g else g.copy(title = zh)
		}
}
