package io.misode.mobile

/**
 * 生成器 id → 数据包 / 资源包内的目录。
 *
 * misode 只负责生成文件内容，不告诉宿主该写到哪。
 * 而写错位置游戏是完全静默的 —— 文件在那儿、但不生效，
 * 这正是之前「写不出来数据包」的表现。
 *
 * 目录规则按 Minecraft 的数据包格式推：
 *   · `worldgen/xxx` → `data/<ns>/worldgen/xxx/`
 *   · `tag/xxx`     → `data/<ns>/tags/xxx/`
 *   · 其余走复数，少数（dimension 等）保持单数
 */
internal object MisodePaths {

	enum class Kind { DATA, ASSET, NONE }

	data class Target(val kind: Kind, val dir: String)

	private val MAP: Map<String, Target> = mapOf(
		"loot_table" to Target(Kind.data, "loot_tables"),
		"predicate" to Target(Kind.data, "predicates"),
		"item_modifier" to Target(Kind.data, "item_modifiers"),
		"advancement" to Target(Kind.data, "advancements"),
		"recipe" to Target(Kind.data, "recipes"),
		"chat_type" to Target(Kind.data, "chat_types"),
		"damage_type" to Target(Kind.data, "damage_types"),
		"trim_material" to Target(Kind.data, "trim_materials"),
		"trim_pattern" to Target(Kind.data, "trim_patterns"),
		"banner_pattern" to Target(Kind.data, "banner_patterns"),
		"wolf_variant" to Target(Kind.data, "wolf_variants"),
		"wolf_sound_variant" to Target(Kind.data, "wolf_sound_variants"),
		"enchantment" to Target(Kind.data, "enchantments"),
		"enchantment_provider" to Target(Kind.data, "enchantment_providers"),
		"painting_variant" to Target(Kind.data, "painting_variants"),
		"jukebox_song" to Target(Kind.data, "jukebox_songs"),
		"instrument" to Target(Kind.data, "instruments"),
		"trial_spawner" to Target(Kind.data, "trial_spawners"),
		"pig_variant" to Target(Kind.data, "pig_variants"),
		"pig_sound_variant" to Target(Kind.data, "pig_sound_variants"),
		"cat_variant" to Target(Kind.data, "cat_variants"),
		"cat_sound_variant" to Target(Kind.data, "cat_sound_variants"),
		"frog_variant" to Target(Kind.data, "frog_variants"),
		"chicken_variant" to Target(Kind.data, "chicken_variants"),
		"chicken_sound_variant" to Target(Kind.data, "chicken_sound_variants"),
		"context_float_provider" to Target(Kind.data, "context_float_providers"),
		"context_int_provider" to Target(Kind.data, "context_int_providers"),
		"cow_variant" to Target(Kind.data, "cow_variants"),
		"cow_sound_variant" to Target(Kind.data, "cow_sound_variants"),
		"dialog" to Target(Kind.data, "dialogs"),
		"test_instance" to Target(Kind.data, "test_instances"),
		"test_environment" to Target(Kind.data, "test_environments"),
		"timeline" to Target(Kind.data, "timelines"),
		"zombie_nautilus_variant" to Target(Kind.data, "zombie_nautilus_variants"),
		"world_clock" to Target(Kind.data, "world_clocks"),
		"villager_trade" to Target(Kind.data, "villager_trades"),
		"trade_set" to Target(Kind.data, "trade_sets"),
		"sulfur_cube_archetype" to Target(Kind.data, "sulfur_cube_archetypes"),
		"slot_source" to Target(Kind.data, "slot_sources"),
		"decorated_pot_pattern" to Target(Kind.data, "decorated_pot_patterns"),
		"block_transformer" to Target(Kind.data, "block_transformers"),
		"text_component" to Target(Kind.none, ""),
		"pack_mcmeta" to Target(Kind.none, ""),
		"dimension" to Target(Kind.data, "dimension"),
		"dimension_type" to Target(Kind.data, "dimension_type"),
		"worldgen/biome" to Target(Kind.data, "worldgen/biome"),
		"worldgen/configured_carver" to Target(Kind.data, "worldgen/configured_carver"),
		"worldgen/carver" to Target(Kind.data, "worldgen/carver"),
		"worldgen/configured_feature" to Target(Kind.data, "worldgen/configured_feature"),
		"worldgen/feature" to Target(Kind.data, "worldgen/feature"),
		"worldgen/placed_feature" to Target(Kind.data, "worldgen/placed_feature"),
		"worldgen/density_function" to Target(Kind.data, "worldgen/density_function"),
		"worldgen/material_condition" to Target(Kind.data, "worldgen/material_condition"),
		"worldgen/material_rule" to Target(Kind.data, "worldgen/material_rule"),
		"worldgen/noise" to Target(Kind.data, "worldgen/noise"),
		"worldgen/noise_settings" to Target(Kind.data, "worldgen/noise_settings"),
		"worldgen/configured_structure_feature" to Target(Kind.data, "worldgen/configured_structure_feature"),
		"worldgen/structure" to Target(Kind.data, "worldgen/structure"),
		"worldgen/structure_set" to Target(Kind.data, "worldgen/structure_set"),
		"worldgen/configured_surface_builder" to Target(Kind.data, "worldgen/configured_surface_builder"),
		"worldgen/processor_list" to Target(Kind.data, "worldgen/processor_list"),
		"worldgen/template_pool" to Target(Kind.data, "worldgen/template_pool"),
		"worldgen/world_preset" to Target(Kind.data, "worldgen/world_preset"),
		"worldgen/flat_level_generator_preset" to Target(Kind.data, "worldgen/flat_level_generator_preset"),
		"world" to Target(Kind.none, ""),
		"tag/block" to Target(Kind.data, "tags/block"),
		"tag/entity_type" to Target(Kind.data, "tags/entity_type"),
		"tag/fluid" to Target(Kind.data, "tags/fluid"),
		"tag/game_event" to Target(Kind.data, "tags/game_event"),
		"tag/item" to Target(Kind.data, "tags/item"),
		"tag/damage_type" to Target(Kind.data, "tags/damage_type"),
		"tag/dialog" to Target(Kind.data, "tags/dialog"),
		"tag/worldgen/biome" to Target(Kind.data, "tags/worldgen/biome"),
		"tag/worldgen/structure" to Target(Kind.data, "tags/worldgen/structure"),
		"tag/worldgen/structure_set" to Target(Kind.data, "tags/worldgen/structure_set"),
		"tag/worldgen/flat_level_generator_preset" to Target(Kind.data, "tags/worldgen/flat_level_generator_preset"),
		"tag/worldgen/world_preset" to Target(Kind.data, "tags/worldgen/world_preset"),
		"tag/banner_pattern" to Target(Kind.data, "tags/banner_pattern"),
		"tag/cat_variant" to Target(Kind.data, "tags/cat_variant"),
		"tag/enchantment" to Target(Kind.data, "tags/enchantment"),
		"tag/instrument" to Target(Kind.data, "tags/instrument"),
		"tag/painting_variant" to Target(Kind.data, "tags/painting_variant"),
		"tag/point_of_interest_type" to Target(Kind.data, "tags/point_of_interest_type"),
		"tag/timeline" to Target(Kind.data, "tags/timeline"),
		"tag/zombie_nautilus_variant" to Target(Kind.data, "tags/zombie_nautilus_variant"),
		"tag/villager_trade" to Target(Kind.data, "tags/villager_trade"),
		"tag/trade_set" to Target(Kind.data, "tags/trade_set"),
		"block_definition" to Target(Kind.asset, "blockstates"),
		"item_definition" to Target(Kind.asset, "items"),
		"model" to Target(Kind.asset, "models"),
		"texture_meta" to Target(Kind.asset, "textures"),
		"equipment" to Target(Kind.asset, "equipment"),
		"lang" to Target(Kind.asset, "lang"),
		"font" to Target(Kind.asset, "font"),
		"atlas" to Target(Kind.asset, "atlases"),
		"post_effect" to Target(Kind.asset, "post_effect"),
		"sounds" to Target(Kind.asset, ""),
		"ad_astra:planets" to Target(Kind.none, ""),
		"fabric:fabric_mod_json" to Target(Kind.none, ""),
		"fabric:dependency_overrides" to Target(Kind.none, ""),
		"immersive_weathering:block_growth" to Target(Kind.none, ""),
		"neoforge:biome_modifier" to Target(Kind.none, ""),
		"neoforge:data_map_acceptable_villager_distances" to Target(Kind.none, ""),
		"neoforge:data_map_compostables" to Target(Kind.none, ""),
		"neoforge:data_map_furnace_fuels" to Target(Kind.none, ""),
		"neoforge:data_map_monster_room_mobs" to Target(Kind.none, ""),
		"neoforge:data_map_oxidizables" to Target(Kind.none, ""),
		"neoforge:data_map_parrot_imitations" to Target(Kind.none, ""),
		"neoforge:data_map_raid_hero_gifts" to Target(Kind.none, ""),
		"neoforge:data_map_strippables" to Target(Kind.none, ""),
		"neoforge:data_map_vibration_frequencies" to Target(Kind.none, ""),
		"neoforge:data_map_villager_types" to Target(Kind.none, ""),
		"neoforge:data_map_waxables" to Target(Kind.none, ""),
		"neoforge:structure_modifier" to Target(Kind.none, ""),
		"ohthetreesyoullgrow:configured_feature" to Target(Kind.none, ""),
		"sky_aesthetics:sky" to Target(Kind.none, ""),
		"create:recipes" to Target(Kind.none, ""),
		"loot-table-modifier:loot_modifier" to Target(Kind.none, ""),
		"thermoo:environment_provider" to Target(Kind.none, ""),
		"thermoo:environment" to Target(Kind.none, ""),
		"thermoo:temperature_effect" to Target(Kind.none, ""),
		"thermoo:predicate" to Target(Kind.none, ""),
		"pixelmon:raid_ally_set" to Target(Kind.none, ""),
		"pixelmon:raid_spawn_set" to Target(Kind.none, ""),
		"pixelmon:growth" to Target(Kind.none, ""),
		"pixelmon:type" to Target(Kind.none, ""),
		"pixelmon:spawn_replacement" to Target(Kind.none, ""),
		"pixelmon:interaction_event" to Target(Kind.none, ""),
		"pixelmon:research" to Target(Kind.none, ""),
		"pixelmon:research_trigger" to Target(Kind.none, ""),
		"pixelmon:npc_preset" to Target(Kind.none, ""),
		"pixelmon:pokedex_trigger" to Target(Kind.none, ""),
		"pixelmon:pokedex_region" to Target(Kind.none, ""),
		"pixelmon:pokedex" to Target(Kind.none, ""),
		"lychee:recipe" to Target(Kind.none, ""),
		"starexpress:guidebook_entry" to Target(Kind.none, ""),
		"treeplacer:sapling_overrides" to Target(Kind.none, ""),
	)

	/** 目录名；dir 为空表示文件直接放在包根（如 sounds.json）。 */
	fun of(id: String): Target? = MAP[id]

	fun isDatapack(id: String): Boolean = MAP[id]?.kind == Kind.DATA
}
